version: "3.7"

services:
  utils:
    container_name: utils
    build:
      context: docker/nestjs
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./graphql:/graphql
      - ./grpc/proto:/proto
    working_dir: /app
      