version: "3.7"

services:
  utils:
    container_name: utils
    build:
      context: docker/nestjs
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./prisma:/prisma
      - ../:/main # <- main project that include this
    working_dir: /app  